version: '3.8'
services:
  web:
    image: node:16  # Substitua pelo nome da imagem que você deseja usar
    container_name: backendsalao-web-1
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Monte seu diretório atual no contêiner para desenvolvimento
    working_dir: /app
    command: ["npm", "start"]  # Ou o comando que você usa para iniciar o aplicativo
    depends_on:
      - db
    networks:
      - backendsalao-network

  db:
    image: mysql:8
    container_name: backendsalao-db-1
    environment:
      MYSQL_ROOT_PASSWORD: WFOSgvAITzdDhtkfhXXbUEdJzhExIPud
      MYSQL_DATABASE: railway
    ports:
      - "3308:3306"  # Mapeie a porta 3308 no host para a porta 3306 no contêiner
    networks:
      - backendsalao-network

networks:
  backendsalao-network:
    driver: bridge
