version: '3.8'
services:
  web:
    image: node:16
    container_name: backendsalao-web-1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "start"]
    depends_on:
      - db
    networks:
      - backendsalao-network

  db:
    image: mysql:8
    container_name: backendsalao-db-1
    environment:
      MYSQL_ROOT_PASSWORD: WFOSgvAITzdDhtkfhXXbUEdJzhExIPud
      MYSQL_DATABASE: railway
    ports:
      - "27552:3306"
    networks:
      - backendsalao-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  backendsalao-network:
    driver: bridge
